### PR TITLE
SPDY -> HTTP/2, fix #102

### LINKED ISSUE #102: no longer mention speedy, but http 2.0

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by skddc** [comment]
As HTTP/2 is not widely deployed yet, it'd make sense to make this a "SPDY or HTTP/2". No?

**Comment by untitaker** [comment]
Is SPDY more widely deployed?

**Comment by skddc** [comment]
Yes. We use it at 5apps since quite a while with OpenResty (an Nginx distro). It's also highly recommend to enable either SPDY or HTTP/2, because it increases performance considerably in the case of most RS apps.

**Comment by michielbdejong** [comment]
SPDY is still allowed of course, because it does no harm when the client doesn't support it. But when you build a new server, it's better to use HTTP/2 as that's now the official one.

**Comment by skddc** [comment]
Ok, I don't really care much. :)

**Comment by untitaker** [comment]
:100:

**Pull request merged**
