### PR TITLE
Identify app by origin of redirect_uri

### LINKED ISSUE #101: use client_id to identify clients
We ran into a little problem when using `redirect_uri` to identify a client. Some clients, Sharesome, Webmarks, can have different redirect URIs depending on the URL you start the RS widget from. 

@skddc and I discussed this and came to the conclusion that it _does_ make sense to use `client_id` as identifier. RS.js already uses the same value as `Origin`, so it makes sense to use the value of `client_id` as something to show the user instead of `redirect_uri`.

Proposal for the specification:

> The OAuth server MUST use `client_id` as the unique client identifier and communicate this to the 
> resource owner when requesting authorization. It MUST be equal to the `Origin` header if this is 
> sent by the web browser. The `redirect_uri` MUST contain the same FQDN as the `client_id` 
> and `Origin`. The `client_id`, `redirect_uri` and `Origin` MUST all use the HTTPS scheme.

For example, suppose an application is running on `https://sharesome.5apps.com/`. The `Origin` sent by the browser is then `https://sharesome.5apps.com` (does NOT contain path, NOT a valid URL!), the `client_id` will be `https://sharesome.5apps.com` and the `redirect_uri` can be for example `https://sharesome.5apps.com/` or `https://sharesome.5apps.com/history` (does contain path, valid URL!)

### PR DESCRIPTION
**Pull request by michielbdejong**
Fixes #101

### CODE REVIEW

**Comment by fkooman** [comment]
Also describe what origin is, including example. Does it include scheme? Does it include port? Does it include port when it is the standard port?

**Comment by untitaker** [comment]
>Does it include port when it is the standard port?

For just the differentiation it doesn't matter. Origin is already defined by other RFCs I think, it'd be nice to link to them.

**Comment by fkooman** [comment]
No, it is not just nice, it DOES matter. Please let's just make everything explicit instead of promoting handwaving at every single GH issue.

**Comment by skddc** [comment]
+1 for linking a good definition.

**Comment by untitaker** [comment]
I didn't say I'm against making everything explicit.

**Comment by fkooman** [comment]
In php-remote-storage I use the "Origin" of the redirect_uri. The definition of Origin: scheme + host + port (if non standard). Also URLs with schemes other than HTTP(S) are allowed. If the scheme is 'http', the user gets a warning that the access token may be compromised.

Just realized I don't 'normalize' the redirect_uri. Good stuff!

**Comment by michielbdejong** [comment]
@fkooman can you improve #101 so it's clearer about what 'origin' means? What does the OAuth spec say about non-https schemes in redirect_uri's?

**Comment by fkooman** [comment]
https://tools.ietf.org/html/rfc6749#section-3.1.2.1

```
3.1.2.1.  Endpoint Request Confidentiality

   The redirection endpoint SHOULD require the use of TLS as described
   in Section 1.6 when the requested response type is "code" or "token",
   or when the redirection request will result in the transmission of
   sensitive credentials over an open network.  This specification does
   not mandate the use of TLS because at the time of this writing,
   requiring clients to deploy TLS is a significant hurdle for many
   client developers.  If TLS is not available, the authorization server
   SHOULD warn the resource owner about the insecure endpoint prior to
   redirection (e.g., display a message during the authorization
   request).

   Lack of transport-layer security can have a severe impact on the
   security of the client and the protected resources it is authorized
   to access.  The use of transport-layer security is particularly
   critical when the authorization process is used as a form of
   delegated end-user authentication by the client (e.g., third-party
   sign-in service).
```

**Comment by fkooman** [comment]
The `Origin` algorithm I'd like to propose is from RF 6454 "The Web Origin Concept", in particular section 4 "Origin of a URI": See https://tools.ietf.org/html/rfc6454#section-4

**Comment by fkooman** [comment]
is this now actually solved? it does not say that client_id needs to match the origin of redirect_uri?

**Comment by skddc** [comment]
Yeah, I'm missing that as well. I thought I saw it in a an earlier change.

**Comment by michielbdejong** [comment]
@fkooman True, we only changed the suggestion to use the `redirect_uri` to using the *origin of* the `redirect_uri`. But this suggestion was, and is still is, a MAY, and only applies if the server does not require client registration (most servers currently, right?).

It doesn't need to match (and probably will not) if the server requires client registration. 

The "it MUST still be sent and valid" part is a bit weird in the middle there, because it's a MUST for clients, and the rest of the sentence describes the server's perspective.

So maybe we should have another go at this, and state that, unless client registration is used, the server SHOULD (not MAY) reject any OAuth requests where `client_id` does not match the Origin of `redirect_uri` (breaking for both servers & clients).

And we could add a sentence explaining that revokation and reuse of already existing tokens should be per `client_id`, not per `redirect_uri`.

**Comment by skddc** [comment]
> So maybe we should have another go at this, and state that, unless client registration is used, the server SHOULD (not MAY) reject any OAuth requests where client_id does not match the Origin of redirect_uri (breaking for both servers & clients).
> 
> And we could add a sentence explaining that revokation and reuse of already existing tokens should be per client_id, not per redirect_uri.

:+1:

**Comment by untitaker** [comment]
On 26 November 2015 14:37:11 CET, Michiel de Jong <notifications@github.com> wrote:

>The "it MUST still be sent and valid" part is a bit weird in the middle
>there, because it's a MUST for clients, and the rest of the sentence
>describes the server's perspective.
>

I've opened a PR for that yesterday, +1 on the rest.
-- 
Sent from my phone. Please excuse my brevity.

**Pull request merged**
