### PR TITLE
Version 09

### PR DESCRIPTION
**Pull request by michielbdejong**
I just noticed that #151 was merged into master, but then accidentally not included in the -08 text. This means the changelog was incorrect, I included a commit to this PR that corrects it.
Other than the change from #151 there are no changes since -08 (or since -07, for that matter). 

@skddc @jancborchardt and other people who are in Berlin atm, we could meet at c-base tonight by way of release party? :)

### CODE REVIEW

**Comment by skddc** [comment]
> @skddc @jancborchardt and other people who are in Berlin atm, we could meet at c-base tonight by way of release party? :)

YES! :)

**Comment by skddc** [comment]
+1

(Plus "everyone at the table" at c-base 😉)

**Comment by skddc** [comment]
img_20170602_210857

**Comment by silverbucket** [comment]
I'm there in spirit!

**Comment by jancborchardt** [comment]
Nice! I'm too spent to join but have fun! :)

**Pull request merged**
