### PR TITLE
remove PUT range request mention, issue #117

### PR DESCRIPTION
**Pull request by fkooman**

### CODE REVIEW

**Comment by untitaker** [comment]
Tbh all of those examples seem pointless.

**Comment by untitaker** [comment]
Argh nevermind, we actually need the content-range example.

**Comment by untitaker** [comment]
Would be nice if commit message includes some sort of rationale, i.e. https://github.com/remotestorage/spec/issues/124#issuecomment-159974966

:+1: though.

**Comment by michielbdejong** [comment]
What's wrong with range headers on PUT requests? The Google Drive API uses them as well, very useful! https://developers.google.com/drive/web/manage-uploads#resumable

r-

**Comment by fkooman** [comment]
Sigh.

There is nothing wrong with it, but this is the first time you mention a document where it is explained *how* to do this. So If you want to support this proprietary Google protocol for doing range request uploads (and introducing POST in the process) then let's mention this URL in the specification!

**Comment by fkooman** [comment]
See also https://github.com/remotestorage/spec/issues/124#issuecomment-159974966

**Comment by michielbdejong** [comment]
So https://developers.google.com/drive/web/manage-uploads#resumable is a direct violation of https://github.com/remotestorage/spec/issues/124#issuecomment-159994866 then? Shocking! :)

**Comment by michielbdejong** [comment]
Merged in fabeaac.

**Pull request closed without merging**
