### PR TITLE
Allow leaving out 'me@' in user address

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
Fixes #85

**Comment by fkooman** [comment]
Common way WF query should be then:

`?resource=https%2E%2F%2Fhost%2Ecom`

**Comment by fkooman** [comment]
https://tools.ietf.org/html/rfc7033#section-4.1 for encoding rules for WebFinger queries

**Comment by fkooman** [comment]
+1

**Comment by untitaker** [comment]
Are servers required to implement this?

**Comment by fkooman** [comment]
No. It makes no sense for a server to implement this, it is purely a WebFinger thingy on the user domain when you use your own storage server or a delegated server.

**Comment by untitaker** [comment]
I'm confused. Where is the `http://`-format used then? I couldn't find anything relevant in the cited WebFinger RFC section.

**Comment by fkooman** [comment]
It is not, but instead of `acct:me@michielbdejong.com` it would query `http://michielbdejong.com`. it is a hack where @michielbdejong doesn't need to type `me@` any longer :)

**Comment by untitaker** [comment]
So instead of GET-ting this:

    http://server.com/.well-known/webfinger?resource=acct:me@bla.com

We GET:

    http://server.com/.well-known/webfinger?resource=http://bla.com

Right?

**Comment by fkooman** [comment]
Almost, the resource value needs to be URI encoded.

**Comment by untitaker** [comment]
Oh, yeah sure. So my point is, how does this not require server support? I don't use a generic webfinger library.

**Comment by fkooman** [comment]
This is **only** relevant if you have your own domain with only one user and point to your (or some hosted) RS server. The WebFinger would be on your own domain, NOT on the RS server.

The only reason, my, and possibly other RS servers *also* include WebFinger is because no one has their own domain set up correctly for HTTPS and WebFinger to be able to point to the server instance.

**Comment by untitaker** [comment]
So what you're saying is that you made the spec more confusing for a very specific unpopular usecase? :P

**Comment by fkooman** [comment]
Choose your battles...

**Comment by untitaker** [comment]
Oh well, just recapping my issues with this:

* Currently it is not clear whether servers *have* to support this kind of query.
* We now have two formats for account ids: `user@host` and `host`. Negative impact on UX?
* Added value dubious IMO

**Comment by michielbdejong** [comment]
It's up to the server to decide which person is identified by which URI. So this is a breaking change for clients, not for servers (we'll list it like that in the changelog and in the release notes).

**Comment by untitaker** [comment]
@michielbdejong Could we have a proper discussion about this? I think it'll be damaging to the protocol.

**Comment by michielbdejong** [comment]
@untitaker I added this in an attempt to modernize our protocol a bit :) These days, indieweb (one domain name per world citizen) is more popular than webfinger - most people who supported webfinger in its day are now supporting indieweb. Requiring clients to support single-user servers that use `domain.com` as their identifier (as advocated for instance by https://indieauth.com/) does not affect the requirements for (IDP) servers that do have multiple users, and IIRC, remotestorage.js already supports it anyway.

**Comment by untitaker** [comment]
As said in IRC, that's a bad technical reason. It has been shown that users are much more willing to accept an email-like string as their identity, and not a URL. They say "foobar on Twitter", not "twitter dot com slash foobar". And OpenID has probably failed because of this.

**Comment by skddc** [comment]
> And OpenID has probably failed because of this.

I'd say so too, and [OpenID Connect](https://openid.net/connect/) actually uses Webfinger now and is already deployed by many of the biggest companies on the Web, incl. Google, Microsoft and PayPal.

**Comment by fkooman** [comment]
> I'd say so too

And that's why Persona succeeded? ;)

**Comment by untitaker** [comment]
I'm not claiming Webfinger is guaranteeing success.

**Comment by skddc** [comment]
> And that's why Persona succeeded? ;)

Are you saying it failed because people used email addresses as identifiers? Come on.

**Comment by fkooman** [comment]
Got a little off topic now, but I meant to say that there may be more reasons than just the use of URLs in OpenID that it failed...

**Comment by skddc** [comment]
Yes, but a lot of people agree that it was one of the big ones. It was supported by a ton of companies, and it was evident that user adoption was the issue, as opposed to provider adoption. And I know what I saw when I watched people trying to understand what they had to enter in that field.

**Comment by untitaker** [comment]
Either way we currently allow both, for no good reason other than "indieweb people like it that way". This is pure appeasement politics, even to a minority that in no way represents the entire audience we actually want to target.

**Comment by skddc** [comment]
I guess the question is, if we want to target people who self-host everything just for their own person, does it make sense for them to be able to use `myfirstandlastname.com` as opposed to having to invent a user name for themselves that goes in front of their name domain just because it's required.

**Comment by untitaker** [comment]
This usecase is perfectly covered with email-like identifiers. I don't see a need for specializing the protocol for a usecase that already works fine.

**Comment by fkooman** [comment]
We could standardize the email-like identifiers (+webfinger) and MAY support other discovery methods.

**Comment by michielbdejong** [comment]
Rather than an 'appeasement', I would say it's us showing support for the 'log in with your domain' initiative where every human owns a domain name, which I think is a nice thing in terms of decentralization.

**Comment by untitaker** [comment]
We could also go the route of having a default username, which is automatically appended **client-side**.

**Comment by skddc** [comment]
> We could also go the route of having a default username, which is automatically appended client-side.

It's not a requirement for the server side in any case however. You can only use a domain name if your server explicitly supports it, and as someone using their own domain name, they should definitely know.

Appending it client-side sounds like a hack to me, whereas supporting a different format for the account parameter (which is also valid), does not. Not withstanding the fact, that your idea might be slightly easier to implement for clients.

Another issue I see with this is validation of user address input and the UX in case a normal user (without their own domain) type something that is not a user@host address.

**Comment by untitaker** [comment]
It needs client-side support in either case, because clients still need to extract the hostname from either format to send webfinger requests to.

**Comment by skddc** [comment]
Yes of course. My point was that allowing it on the server just seems cleaner to me if we're going to allow it at all.

**Pull request merged**
