### PR TITLE
Bump spec version to -08

### PR DESCRIPTION
**Pull request by michielbdejong**
There are not currently any open pull requests on the spec, so bumping the version from -07 to -08 with the same text.

There were two places in the text where we forgot to bump from -06 to -07 in June, so bumping those straight to -08 now.

There are three weeks left until spec -08 is due to go live - if there are any [open issues](https://github.com/remotestorage/spec/issues) you would like to see addressed in this version, or any changes you would like to see included, please create a pull request for them.

### CODE REVIEW

**Comment by untitaker** [comment]
Some issues need discussion before a PR can be opened

**Comment by michielbdejong** [comment]
@untitaker which of the open issues, if any, would you like to be addressed before we tag -08?

**Comment by untitaker** [comment]
https://github.com/remotestorage/spec/issues/130 and everything I labeled with "bug".

**Comment by michielbdejong** [comment]
Continued in #153

**Pull request closed without merging**
