### PR TITLE
Add 413 as example response code

### LINKED ISSUE #106: add 413 (payload too large) to list of supported response codes
https://tools.ietf.org/html/rfc7231#section-6.5.11

### PR DESCRIPTION
**Pull request by skddc**
closes #106

### CODE REVIEW

**Comment by skddc** [comment]
@michielbdejong @fkooman Ping.

**Comment by michielbdejong** [comment]
LGTM!

**Comment by skddc** [comment]
@michielbdejong Do we need @fkooman's +1 or can you merge it?

**Comment by fkooman** [comment]
I'm okay with everything!

**Comment by michielbdejong** [comment]
@skddc can this be merged?

**Comment by skddc** [comment]
I don't know, you're the editor and I proposed a change. No idea if you want a second review from @fkooman.

**Comment by michielbdejong** [comment]
I think his "okay with everything" is good enough as a second review :)

**Pull request merged**
